name: fts5_simple
description: A flutter plugin wrapper for Simple tokenizer (https://github.com/wangfenjin/simple), improve your fts5 search for Chinese.
version: 0.0.1
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/master/packages/fts5_simple

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.1
  sqlite3: ^1.3.1
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiercshould not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      windows:
        pluginClass: Fts5SimplePlugin
      macos:
        pluginClass: Fts5SimplePlugin
      linux:
        pluginClass: Fts5SimplePlugin
      ios:
        pluginClass: Fts5SimplePlugin

  assets:
    - dicts/
