name: pasteboard
description: A flutter plugin which could read image,files from clipboard and write files to clipboard.
version: 0.2.0
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/pasteboard

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  uuid: ^4.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^2.0.0"

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: PasteboardPlugin
      windows:
        pluginClass: PasteboardPlugin
      linux:
        pluginClass: PasteboardPlugin
      ios:
        pluginClass: PasteboardPlugin
      web:
