name: mixin_logger
description: Simple logger tool for flutter, make it easy to save your app log to file.
version: 0.0.6
homepage: https://github.com/MixinNetwork/flutter-plugins

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^2.0.1
  path: ^1.8.0
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.17.0
  ffigen: ^6.1.2


flutter:
  plugin:
    platforms:
      macos:
        pluginClass: MixinLoggerPlugin
